#!/usr/bin/env python3
# m1_diff.py — differential for milestone 1 of the thm 5.2 formalization:
# Lean SgoSerial.sgoEv vs the engine's independent step_state. Random
# full-game playouts (passes, collisions, double-pass endings) on 3x3 and
# 5x5, plus unavailability probes tested inline (linear, no replays).
# Cases are STRING-encoded to keep Lean elaboration cheap; emits
# TestSerial.lean with a native_decide checker.
import random, sys
sys.path.insert(0, '/home/claude/sgo')
import sgo_engine as E

random.seed(2137)

def enc_disp(board, ts, N):
    out = []
    for x in range(N):
        for y in range(N):
            p = (x, y)
            out.append(f"{board[p]}{ts.get(p, 0)}" if p in board else ".")
    return ",".join(out)

def enc_branch(a, N):
    return "".join(a.get((x, y), ".") for x in range(N) for y in range(N))

def rand_move(board, N, pass_p):
    if random.random() < pass_p:
        return None
    empties = [(x, y) for x in range(N) for y in range(N) if (x, y) not in board]
    if not empties:
        return None
    return random.choice(empties)

def mstr(m):
    return "p" if m is None else str(m)

def gen_games(N, games, maxt, probe_p):
    cases = []
    inv_count = 0
    for g in range(games):
        board, ts, branches = {}, {}, [dict()]
        n = 1
        moves, disps, ents, fins, probes = [], [], [], [], []
        prev_disp = enc_disp(board, ts, N)
        prev_ent = sorted({enc_branch(a, N) for a in branches})
        for turn in range(maxt):
            # unavailability probes at the CURRENT state (pre-move)
            pr = []
            if board and random.random() < probe_p:
                occ = random.choice(list(board.keys()))
                other = rand_move(board, N, 0.2)
                a = occ[0] * N + occ[1]
                b = None if other is None else other[0] * N + other[1]
                pr.append((a, b) if random.random() < 0.5 else (b, a))
            probes.append(pr)
            m0 = rand_move(board, N, 0.10)
            m1 = rand_move(board, N, 0.10)
            if m0 is not None and random.random() < 0.10:
                m1 = m0  # collision
            if m0 is None and m1 is None:
                moves.append((None, None))
                disps.append(prev_disp); ents.append(prev_ent); fins.append(True)
                break
            board, ts, branches = E.step_state(board, ts, branches, n, m0, m1, N)
            if E.check_invariant(board, branches):
                inv_count += 1
            n += 1
            prev_disp = enc_disp(board, ts, N)
            prev_ent = sorted({enc_branch(a, N) for a in branches})
            moves.append((m0[0] * N + m0[1] if m0 else None,
                          m1[0] * N + m1[1] if m1 else None))
            disps.append(prev_disp); ents.append(prev_ent); fins.append(False)
            if len(branches) > 40 or not branches:
                break
        movesS = ";".join(f"{mstr(a)}:{mstr(b)}" for a, b in moves)
        dispsS = "|".join(disps)
        entsS = "|".join(",".join(bs) for bs in ents)
        finsS = "".join("1" if f else "0" for f in fins)
        probesS = "|".join(" ".join(f"{mstr(a)}:{mstr(b)}" for a, b in pr)
                           for pr in probes[:len(moves)])
        cases.append((N, movesS, dispsS, entsS, finsS, probesS))
    return cases, inv_count

HEADER = r'''/- TestSerial.lean — GENERATED by m1_diff.py. Differential: sgoEv vs the
   engine's step_state on random playouts (passes, collisions, double-pass
   endings), with inline unavailability probes. String-encoded cases. -/
import SgoSerial
open SgoGo SgoDisplay SgoSerial

structure GCase where
  n : Nat
  movesS : String
  dispsS : String
  entsS : String
  finsS : String
  probesS : String

def kindChar : DKind → String | .b => "b" | .w => "w" | .r => "r"

def encDisp (n : Nat) (D : Display n) : String :=
  String.intercalate "," ((allIdx n).map fun i =>
    match D.get i with
    | none => "."
    | some (k, st) => kindChar k ++ toString st)

def encBranch (n : Nat) (b : Display n) : String :=
  ((allIdx n).map fun i =>
    match kindAt b i with
    | none => "." | some k => kindChar k).foldl (· ++ ·) ""

def setEq (xs ys : List String) : Bool :=
  xs.all ys.contains && ys.all xs.contains

def dMv (s : String) : Option Nat :=
  if s == "p" then none else some s.toNat!

def dPair (s : String) : Option Nat × Option Nat :=
  match s.splitOn ":" with
  | [a, b] => (dMv a, dMv b)
  | _ => (some 999999, some 999999)

def dPairs (s : String) : List (Option Nat × Option Nat) :=
  if s == "" then [] else (s.splitOn " ").map dPair

def runSteps (n : Nat) : SGoState n → List (String × (String × (String × (Char × String)))) → Bool
  | _, [] => true
  | s, (mv, (d, (es, (f, prS)))) :: rest =>
    -- probes at the pre-state: all must be unavailable
    ((dPairs prS).all fun (a, b) => (sgoEv n s a b).isNone) &&
    (let (m0, m1) := dPair mv
     match sgoEv n s m0 m1 with
     | none => false
     | some s' =>
       encDisp n s'.disp == d &&
       setEq (s'.ent.map (encBranch n)) (if es == "" then [] else es.splitOn ",") &&
       s'.final == (f == '1') &&
       runSteps n s' rest)

def runGame (c : GCase) : Bool :=
  let ms := c.movesS.splitOn ";"
  let ds := c.dispsS.splitOn "|"
  let es := c.entsS.splitOn "|"
  let fs := c.finsS.data
  let ps := c.probesS.splitOn "|"
  ms.length == ds.length && ms.length == es.length &&
  ms.length == fs.length && ms.length == ps.length &&
  runSteps c.n (initSGo c.n) (ms.zip (ds.zip (es.zip (fs.zip ps))))

def cases : List GCase := ['''

TAIL = r''']

/-- The milestone-1 differential: every playout matches the engine turn
    by turn (display with stamps, entanglement as a set, finality), and
    every unavailability probe is rejected. -/
theorem m1_differential : cases.all runGame = true := by native_decide
'''

def emit(cases, path):
    rows = []
    for (N, movesS, dispsS, entsS, finsS, probesS) in cases:
        rows.append(f'  ⟨{N}, "{movesS}", "{dispsS}", "{entsS}", "{finsS}", "{probesS}"⟩,')
    with open(path, "w") as f:
        f.write(HEADER + "\n" + "\n".join(rows) + TAIL)

c3, i3 = gen_games(3, 200, 12, 0.35)
c5, i5 = gen_games(5, 40, 8, 0.35)
allc = c3 + c5
emit(allc, "/home/claude/sgolean/TestSerial.lean")
nt = sum(len(c[1].split(";")) for c in allc)
print(f"games {len(allc)}, turns {nt}, engine occupancy-diagnostic states {i3 + i5}")
